#This file is generated by VisualGDB.
#It contains GCC settings automatically derived from the board support package (BSP).
#DO NOT EDIT MANUALLY. THE FILE WILL BE OVERWRITTEN. 
#Use VisualGDB Project Properties dialog or modify Makefile or per-configuration .mak files instead.

#In order to build this project manually (outside VisualGDB), please provide TOOLCHAIN_ROOT, BSP_ROOT, EFP_BASE and TESTFW_BASE variables via Environment or Make command line
#Embedded toolchain
CC := $(TOOLCHAIN_ROOT)/bin/arm-none-eabi-gcc.exe
CXX := $(TOOLCHAIN_ROOT)/bin/arm-none-eabi-g++.exe
LD := $(CXX)
AR := $(TOOLCHAIN_ROOT)/bin/arm-none-eabi-ar.exe
OBJCOPY := $(TOOLCHAIN_ROOT)/bin/arm-none-eabi-objcopy.exe

#Additional flags
PREPROCESSOR_MACROS += ARM_MATH_CM7 flash_layout STM32F746NE STM32F746xx USE_HAL_DRIVER 
INCLUDE_DIRS += . $(BSP_ROOT)/STM32F7xxxx/STM32F7xx_HAL_Driver/Inc $(BSP_ROOT)/STM32F7xxxx/STM32F7xx_HAL_Driver/Inc/Legacy $(BSP_ROOT)/STM32F7xxxx/CMSIS_HAL/Core/Include $(BSP_ROOT)/STM32F7xxxx/CMSIS_HAL/Device/ST/STM32F7xx/Include $(BSP_ROOT)/STM32F7xxxx/CMSIS_HAL/Include $(BSP_ROOT)/STM32F7xxxx/CMSIS_HAL/RTOS2/Include $(BSP_ROOT)/STM32H7xxxx/BSP/Components/ampire480272 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/Common $(BSP_ROOT)/STM32H7xxxx/BSP/Components/ampire640480 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/exc7200 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/ft5336 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/mfxstm32l152 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/ov9655 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/rk043fn48h $(BSP_ROOT)/STM32H7xxxx/BSP/Components/s5k5cag $(BSP_ROOT)/STM32H7xxxx/BSP/Components/stmpe811 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/ts3510 $(BSP_ROOT)/STM32H7xxxx/BSP/Components/wm8994
LIBRARY_DIRS += 
LIBRARY_NAMES += 
ADDITIONAL_LINKER_INPUTS += 
MACOS_FRAMEWORKS += 
LINUX_PACKAGES += 

CFLAGS += 
CXXFLAGS += 
ASFLAGS += 
LDFLAGS +=  --specs=nosys.specs
COMMONFLAGS += -mcpu=cortex-m7 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard
LINKER_SCRIPT := $(BSP_ROOT)/STM32F7xxxx/LinkerScripts/STM32F746NE_flash.lds

